---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present
    - name: Start & Enable HTTPD Service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes


- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  vars:
      dbname: groups
      dbuser: devops
      dbpass: asd123.
  tasks:
    - debug: 
        var: dbname
    - debug:
        msg: "Value of dbuser is {{dbuser}}"
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
    - name: Install Python MySQL
      yum:
        name: MySQL-python
        state: present
    - name: Start & Enable MariaDB Service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Create database user with database privileges
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present

